/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BurntPixArchives } from "./BurntPixArchives";
export * as factories from "./factories";
export { BurntPixArchives__factory } from "./factories/BurntPixArchives__factory";
