/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HouseOfBurntPix } from "./HouseOfBurntPix";
export * as factories from "./factories";
export { HouseOfBurntPix__factory } from "./factories/HouseOfBurntPix__factory";
